config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /en|pl/ do
    root 'parkings#index'
    resources :parkings do
      resources :place_rents, only: [:new, :create]
    end

    resources :cars
    resources :place_rents, only: [:index, :show]

    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create', as: :session
    delete 'logout', to: 'sessions#destroy', as: :logout
    get 'register', to: 'accounts#new', as: :signup
    post 'register', to: 'accounts#create', as: :accounts
  end

  #get '/:locale', to: 'parkings#index'
  root 'parkings#index', as: nil
  resource :session

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider', to: 'sessions#create', as: 'auth_sign_in'
  get '/auth/failure', to: 'sessions#failure'
end

app/models/place_rent.rb
class PlaceRent < ActiveRecord::Base
  validates :starts_at, :ends_at, :car_id, presence: true
  before_save :set_price
  before_create :generate_random_id

  scope :unfinished, -> { where('ends_at > ?', DateTime.now) }

  belongs_to :car
  belongs_to :parking
  has_one :owner, through: :car

  def to_param
    unique_id
  end

  def calculate_price
    days = (ends_at.to_i - starts_at.to_i) / 1.days
    hours = ((ends_at.to_i - starts_at.to_i) / 1.hour.to_f).ceil - days * 24
    parking.day_price * days + parking.hour_price * hours
  end

  def set_price
    self.price = calculate_price
  end

  def finish
    update_attributes(ends_at: DateTime.now)
  end

  private

  def generate_random_id
    self.unique_id = SecureRandom.uuid
  end
end

app/controllers/place_rents_controller.rb
class PlaceRentsController < ApplicationController
  before_action :authorize_user

  def index
    @place_rents = current_person.place_rents
  end

  def show
    @place_rent = current_person.place_rents.find_by(unique_id: params[:id])
  end

  def new
    @place_rent = PlaceRent.new(parking: parking)
  end

  def create
    @place_rent = current_person.place_rents.new(place_rent_params)
    @place_rent.parking = parking
    if @place_rent.save
      redirect_to @place_rent
    else
      render 'new'
    end
  end

  private

  def place_rent_params
    params.require(:place_rent).permit(:starts_at, :ends_at, :car_id)
  end

  def parking
    @parking ||= Parking.find(params[:parking_id])
  end
end

app/helpers/place_rents_helper.rb
module PlaceRentsHelper
end

app/views/place_rents/_form.html.erb
<%= render partial: 'application/errors', locals: { object: @place_rent } %>

<%= form_for [@parking, @place_rent], html: {class: 'place-rent-form'} do |f| %>

  <p>
    <%= f.label :starts_at %><br>
    <%= f.datetime_select :starts_at %>
  </p>

  <p>
    <%= f.label :ends_at %><br>
    <%= f.datetime_select :ends_at %>
  </p>

  <p>
    <%= f.label :model %><br>
    <%= collection_select :place_rent, :car_id, current_person.cars, :id, :model %>
  </p>

  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/place_rents/index.html.haml
%h1 Place Rents
%div{ class: 'place-rents' }
  %table
    %tr
      %th Start date
      %th End date
      %th Price
      %th Actions
    - @place_rents.each do |place_rent|
      %tr
        %td= place_rent.starts_at
        %td= place_rent.ends_at
        %td= place_rent.price
        %td
          = link_to "Car", car_path(place_rent.car)
          = link_to "Parking", parking_path(place_rent.parking) if place_rent.parking
          = link_to "Show", place_rent_path(place_rent.unique_id), method: 'get'

app/views/place_rents/new.html.erb
<h1>Rent a place</h1>
<%= render 'form' %>

app/views/place_rents/show.html.erb
<%= link_to 'See place rents list', place_rents_path %>
<h1>Place rent details</h1>
Start date: <%= @place_rent.starts_at %></br>
End date: <%= @place_rent.ends_at %></br>