config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /en|pl/ do
    root 'parkings#index'
    resources :parkings do
      resources :place_rents, only: [:new, :create]
    end

    resources :cars
    resources :place_rents, only: [:index, :show]

    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create', as: :session
    delete 'logout', to: 'sessions#destroy', as: :logout
    get 'register', to: 'accounts#new', as: :signup
    post 'register', to: 'accounts#create', as: :accounts
  end

  #get '/:locale', to: 'parkings#index'
  root 'parkings#index', as: nil
  resource :session

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider', to: 'sessions#create', as: 'auth_sign_in'
  get '/auth/failure', to: 'sessions#failure'
end

app/models/parking.rb
class Parking < ActiveRecord::Base
  before_destroy :finish_rents
  KINDS = %w(outdoor indoor private street)

  scope :in_private, -> { where(kind: 'private') }
  scope :in_public, -> { where.not(kind: 'private') }

  validates :places, :hour_price, :day_price, presence: true
  validates :kind, inclusion: { in: KINDS }
  validates :hour_price, :day_price, numericality: true

  belongs_to :address
  belongs_to :owner, class_name: 'Person'
  has_many :place_rents, dependent: :nullify

  accepts_nested_attributes_for :address

  paginates_per 10

  def as_json(options = {})
    super(
      except: [:owner_id, :address_id],
      include: { address: { only: [:id, :street, :city, :zip_code] } }
    )
  end

  def self.day_price_between(from, to)
    where(day_price: from..to)
  end

  def self.hour_price_between(from, to)
    where(hour_price: from..to)
  end

  def self.in_city(city)
    joins(:address).where('city like ?', city)
  end

  def self.search(params)
    ParkingsQuery.new(params).results
  end

  private

  def finish_rents
    place_rents.unfinished.each(&:finish)
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :parking_not_found

  def index
    if params
      @parkings = Parking.search(params).order(:id).page(params[:page])
    else
      @parkings = Parking.order(:id).page(params[:page])
    end

    respond_to do |format|
      format.html
      format.json do
        render json: @parkings
      end
    end
  end

  def show
    parking
    respond_to do |format|
      format.html
      format.json do
        render json: @parking
      end
    end
  end

  def new
    @parking = Parking.new
    parking.build_address
  end

  def create
    @parking = Parking.new(parking_params)
    if parking.save
      redirect_to parkings_path
    else
      render :new
    end
  end

  def edit
    parking
    parking.build_address if parking.address.nil?
  end

  def update
    if parking.update(parking_params)
      redirect_to parkings_path
    else
      render :edit
    end
  end

  def destroy
    parking.destroy
    redirect_to parkings_path
  end

  private

  def parking
    @parking ||= Parking.find(params[:id])
  end

  def parking_not_found
    redirect_to parkings_path, notice: t(:parking_not_found)
  end

  def parking_params
    params.require(:parking).permit(:places,
                                    :kind,
                                    :hour_price,
                                    :day_price,
                                    address_attributes: [
                                      :city,
                                      :street,
                                      :zip_code
                                    ])
  end
end

app/views/parkings/_form.html.erb
<%= render partial: 'application/errors', locals: { object: @parking } %>

<%= form_for @parking, html: {class: 'parking-form'} do |f| %>

  <p>
    <%= f.label :places %>
    <%= f.number_field :places, {min: 0, step: 1} %>
  </p>

  <p>
    <%= f.label :kind %>
    <%= f.select :kind, options_for_select(Parking::KINDS.map { |kind| [t("options.#{kind}"), kind] }) %>
  </p>

  <p>
    <%= f.label :hour_price %>
    <%= f.number_field :hour_price, {min: 0, step: 0.01} %>
  </p>

  <p>
    <%= f.label :day_price %>
    <%= f.number_field :day_price, {min: 0, step: 0.01} %>
  </p>

  <%= f.fields_for :address do |a| %>
    <p>
      <%= a.label :city %>
      <%= a.text_field :city %>
    </p>
    <p>
      <%= a.label :street %>
      <%= a.text_field :street %>
    </p>
    <p>
      <%= a.label :zip_code %>
      <%= a.text_field :zip_code %>
    </p>
  <% end %>

  <p>
    <%= f.submit t(:save) %>
  </p>
<% end %>

app/views/parkings/_search.html.erb
<div class="search-parkings">
  <%= form_tag parkings_path, method: :get do %>
    <p>
      <%= label :private, t('labels.private') %>
      <%= check_box_tag :private, params[:private], params[:private] %>
      <%= label :public, t('labels.public') %>
      <%= check_box_tag :public, params[:public], params[:public] %>
    </p>
      <%= label :day_price_from, t('labels.day_price_from') %>
      <%= text_field_tag :day_price_from, params[:day_price_from] %>
      <%= label :day_price_to, t('labels.day_price_to') %>
      <%= text_field_tag :day_price_to, params[:day_price_to] %>
    <p>
    </p>
      <%= label :hour_price_from, t('labels.hour_price_from') %>
      <%= text_field_tag :hour_price_from, params[:hour_price_from] %>
      <%= label :hour_price_to, t('labels.hour_price_to') %>
      <%= text_field_tag :hour_price_to, params[:hour_price_to] %>
    <p>
    <p>
      <%= label :city, t('labels.city') %>
      <%= text_field_tag :city, params[:city] %>
    </p>
    <p>
      <%= submit_tag t(:search) %>
    </p>
  <% end %>
</div>

app/views/parkings/edit.html.erb
<h1><%= t(:edit_parking) %></h1>
<%= render 'form' %>

app/views/parkings/index.html.haml
%h1= t(:parkings)
= render 'search'
%div{ class: 'parkings' }
  %table
    %tr
      %th= t(:city)
      %th= t(:places)
      %th= t(:hour_price)
      %th= t(:day_price)
      %th= t(:actions)

    - @parkings.each do |parking|
      %tr{ class: 'parking-row' }
        %td= parking.address.try(:city)
        %td= parking.places
        %td= parking.hour_price
        %td= parking.day_price
        %td
          = link_to t(:show), parking_path(parking)
          = link_to t(:edit), edit_parking_path(parking)
          = link_to t(:remove), parking, method: 'delete'
          = link_to t(:rent_a_place), new_parking_place_rent_path(parking) if user_signed_in?
%div= paginate @parkings

app/views/parkings/new.html.erb
<h1><%= t(:add_new_parking) %></h1>
<%= render 'form' %>

app/views/parkings/show.html.erb
<%= link_to t(:see_parkings_list), parkings_path %>
<h1><%= t(:parking_details) %></h1>
<%= Address.human_attribute_name(:city) %>: <%= @parking.address.city %></br>
<%= Address.human_attribute_name(:street) %>: <%= @parking.address.street %></br>
<%= Address.human_attribute_name(:zip_code) %>: <%= @parking.address.zip_code %></br>
<%= Parking.human_attribute_name(:places) %>: <%= @parking.places %></br>
<%= Parking.human_attribute_name(:hour_price) %>: <%= @parking.hour_price %></br>
<%= Parking.human_attribute_name(:day_price) %>: <%= @parking.day_price %>