config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /en|pl/ do
    root 'parkings#index'
    resources :parkings do
      resources :place_rents, only: [:new, :create]
    end

    resources :cars
    resources :place_rents, only: [:index, :show]

    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create', as: :session
    delete 'logout', to: 'sessions#destroy', as: :logout
    get 'register', to: 'accounts#new', as: :signup
    post 'register', to: 'accounts#create', as: :accounts
  end

  #get '/:locale', to: 'parkings#index'
  root 'parkings#index', as: nil
  resource :session

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider', to: 'sessions#create', as: 'auth_sign_in'
  get '/auth/failure', to: 'sessions#failure'
end

app/models/car.rb
class Car < ActiveRecord::Base
  extend Dragonfly::Model
  extend Dragonfly::Model::Validations
  dragonfly_accessor :image

  validates :registration_number, :model, :owner_id, presence: true
  validates_size_of :image, maximum: 200.kilobytes, message: 'should be less than 200 kb.'
  validates_property :format, of: :image, in: %w(jpeg jpg png gif)

  belongs_to :owner, class_name: 'Person'
  has_many :place_rents, dependent: :delete_all

  def to_param
    [id, model.parameterize].join("-")
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :car_not_found
  before_action :authorize_user
  before_action :car, only: [:show, :edit]

  def index
    @cars = current_person.cars.order(:id)
  end

  def new
    @car = Car.new
  end

  def create
    @car = current_person.cars.new(car_params)
    if car.save
      redirect_to cars_path
    else
      render :new
    end
  end

  def update
    if car.update_attributes(car_params)
      redirect_to cars_path
    else
      render :edit
    end
  end

  def destroy
    car.destroy
    redirect_to cars_path
  end

  private

  def car
    @car ||= current_person.cars.find(params[:id])
  end

  def car_not_found
    redirect_to cars_path, notice: 'Car does not exist!'
  end

  def car_params
    params.require(:car).permit(:registration_number, :model, :image, :remove_image, :owner_id)
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= render partial: 'application/errors', locals: { object: @car } %>

<%= form_for @car, html: {class: 'car-form'} do |f| %>

  <p>
    <%= f.label :model, 'Model:' %>
    <%= f.text_field :model %>
  </p>

  <p>
    <%= f.label :registration_number, 'Registration number:' %>
    <%= f.text_field :registration_number %>
  </p>

  <p>
    <% if @car.image_stored? %>
      <%= f.label :image %><br>
      <%= image_tag @car.image.thumb('400x200#').url if @car.image_stored? %>
      <%= f.file_field :image %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
    <% else %>
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    <% end %>
  </p>

  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/cars/edit.html.erb
<h1>Edit car</h1>
<%= render 'form' %>

app/views/cars/index.html.haml
%h1 Cars
%div{ class: 'cars'}
  %table
    %tr
      %th Model
      %th Registration number
    - @cars.each do |car|
      %tr{ class: 'car-row' }
        %td= car.model
        %td= car.registration_number
        %td
          = link_to "Show", car_path(car)
          = link_to "Edit", edit_car_path(car)
          = link_to "Remove", car, :method => :delete

app/views/cars/new.html.erb
<h1>Add new car</h1>
<%= render 'form' %>

app/views/cars/show.html.erb
<%= link_to 'See cars list', cars_path %>
<h1>Car details</h1>
<%if @car.image_stored? %>
  <p><%= image_tag @car.image.thumb('400x200#').url%></p>
<% end %>
<p>Model: <%= @car.model %></p>
<p>Registration number: <%= @car.registration_number %></p>