config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /en|pl/ do
    root 'parkings#index'
    resources :parkings do
      resources :place_rents, only: [:new, :create]
    end

    resources :cars
    resources :place_rents, only: [:index, :show]

    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create', as: :session
    delete 'logout', to: 'sessions#destroy', as: :logout
    get 'register', to: 'accounts#new', as: :signup
    post 'register', to: 'accounts#create', as: :accounts
  end

  #get '/:locale', to: 'parkings#index'
  root 'parkings#index', as: nil
  resource :session

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider', to: 'sessions#create', as: 'auth_sign_in'
  get '/auth/failure', to: 'sessions#failure'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || extract_locale_from_header
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  def extract_locale_from_header
    locales = I18n.available_locales.map(&:to_s)
    language = request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first if request.env['HTTP_ACCEPT_LANGUAGE']
    locales.include?(language) ? language : I18n.default_locale
  end

  helper_method :current_person
  helper_method :current_account
  helper_method :user_signed_in?

  private

  def current_person
    Person.find_by(id: session[:person_id])
  end

  def authorize_user
    return unless current_person.nil?
    session[:return_to] = request.url
    redirect_to login_path, notice: 'Please sign in!'
  end

  def user_signed_in?
    !current_person.nil?
  end

  def sign_in(account)
    if account
      session[:person_id] = account.person_id
      redirect_to session.delete(:return_to) || root_path
    else
      flash.now[:error] = 'Wrong credentials'
      render :new
    end
  end

  def facebook_sign_in(account)
    if account && account.person_id
      session[:person_id] = account.person_id
      redirect_to root_path
    else
      flash.now[:error] = 'Could not login with Facebook'
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    controller_name.humanize
  end

  def flash_class(type)
    case type
    when 'notice' then 'alert alert-info'
    when 'success' then 'alert alert-success'
    when 'error' then 'alert alert-warning'
    when 'alert' then 'alert alert-danger'
    end
  end
end

app/views/application/_errors.html.erb
<% if object.errors.any? %>
  <div class="errors-container" style="background: red; color: white; display: inline-block; padding: 10px; margin-bottom: 30px;">
    <p class="errors">Something went wrong!</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li class="error"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="navbar-header">
    <%= link_to 'ParkApp', root_url, class: 'navbar-brand' %>
  </div>
  <div class="navbar-collapse collapse menu">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Cars', cars_path if user_signed_in? %></li>
      <li><%= link_to 'Parkings', parkings_path %></li>
      <li><%= link_to 'Place rents', place_rents_path if user_signed_in? %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right user">
      <% if current_person %>
        <li>
          <p class="navbar-text">
            Current account: <%= current_person.full_name %>
          </p>
        </li>
        <li>
          <%= link_to 'Sign out', logout_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Sign in', login_path %>
        </li>
        <li>
          <%= link_to 'Sign in with Facebook', auth_sign_in_path('facebook') %>
        </li>
      <% end %>
      <% if I18n.locale != I18n.default_locale %>
        <li >
          <%= link_to 'English', locale: 'en'%>
        </li>
      <% else %>
        <li>
          <%= link_to 'Polski', locale: 'pl'%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>